# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    max-http-form-post-size: 1
  port: 8080
  servlet:
    context-path: /subHub
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false

spring:
  profiles:
    active: subhub
  messages:
    encoding: UTF-8
    basename: i18n/messages
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,classpath:/upload/

subhub:
  redis:
    open: true
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: io.subHub.modules.*.entity,io.subhub.modules.*.*.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: false

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
logging:
  level:
    io.subHub: debug
    com:
      baomidou:
        mybatisplus:
          core:
            mapper=DEBUG:
  file:
    path: ./logs
